# Use root/example as user/password credentials

services:

  mysql:
    image: mysql:9.6.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: worldtravel_db 

    ports:
      - "3307:3306"

    volumes:
      - world-travel-db-volume:/var/lib/mysql 

volumes:
  world-travel-db-volume:
